sudo: false
language: scala
jdk:
- oraclejdk8
scala:
- 2.11.7
- 2.10.6
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test
before_cache:
- find $HOME/.sbt -name "*.lock" -delete
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coveralls
- test "${TRAVIS_TAG}" && sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
env:
  global:
  - secure: 5pTKlnOrIzcEzgGXhtZr/Y/H0+/GUmMVdBlqPfCTADkvA4taAH6vO5Gf27HUJbMMCf+KvaeExGyB06f1SdTbvpECOHGj9cFlTbRbOt4Y4sMADnvWQ+IxnNeBAXSHjNQG3xTTDgWBR87zH92kAxTMLXYpIUrN1Gw7zu+Wu0MdTFrVPgLMLwSLtnGxEXNqMvdTwU4Uej3EjKHalHBzVGAJK2a2QazOr+2gQpyGv+ZUi6OQWkfi7EEmrEgVpeskPYPzjtJ9w78KOwDRe+ilHe+aB3viN9RL6YnGNC7OHKB/Ysh55SszartmqEwCyikn6f1vtUx8iLzq+e3KRFc1ckumZItPciEX1l1NGz8FlAddgFXQ9efWprsNS4ijjjyoEWQQIGTOL77ofmid96RhKyXMkgtief5Izpbg3H+IHoSC/m5dR2/0KEUyAG9V8iuiNnTKm6GzXZ6pCTw9/5vpCMurf9CVreyloGPv3TYgW+2JlOAXqZcbkTXAfAsLW2iHupXKiQRGwa/Ex3pEnIdAxDpZIHb8tGsIrzM0lrO1O2L8INiXYi6z1H60bWvCUokGaCchw+8emjJutxzsZpEKi5jlHz4p7R9ZfYGLfyPxFk+nuJ5Vu0VT2gjpmNIceU1NfLRa/GK/RI6aIqQUeO+zbY7ApF4eNXNyRfi3o26pf+SniEg=
  - secure: l8fdFFjivXUKsFx66LcvdWj5R/M7SK6CYz6iDBsdg8VxUHV3C0SiXhnwmp0642NRCLod6ffKvoifi2yGk/PtU0IVc50yEtdMcAP32zh9dDsVUj415ULPIHlcqJPu9yuYow/hJgmdlifpBOKEVoH6XpNrR8W9dbYt3fjze3GX7TDGNgDl0c3a6uJPL2sIW6KIzut3heuGnjjl3+hZZvF4d5fgaGoSmCy9rOcrpEE4VNCTp6px5mzbU+NTXiUH4JJWqAdNaROhkFanwa6eJoGqBOh9txHjH2+ex+CLGH4IpnRr3gd3RymOqh9QvDnfLtZosz9KKIWD0eKwDF9aGUwnc96BdpIsx4XrDhvBm63RwHODnbwPh5QpfmvxQueNaAQK581v8eBcg65dgrlm3n7yD2wf8/nHsy/7DrEnkO7hNZogijhSm/WEfbkCko0MB18iP0RK5qwafG/EK3YbzMLUemDhC16M+sjQ0EUvACseEdQeH9iIan5ZwOL50HO3cYG47LIe8o8Y0YtDiGKo7ZVSwvb+Cj3lXeLrFUvQt18/fiuQWp2qznxJgwx2DyxNJhbZgKCbX1/y8TA8LDqIL0HGeXDUAotDxvchWcgv2AqkJ2B/6ZA8rsDBX92yH34vzJM++PNlNw+VkgzbRcZvs3PhDFV9GGYnrjd/p/bs1+xX/sQ=
  - secure: 4BZsD3D84SRpj+C0VLmOV4CnrntMPKi4yh65BQpPcFszOirCgbhPJ+XEvyovdC9LYvAuQTw8kSgdYxu6QGiKQNTltlOY5E7JdQI/P6I5Z+d+Kyq8n2QZzoKqIn6ulyhH4pRNbwXRp8vC/lCiXRPnyH0FVO/9j16PeUnbPcJZ++E1DVFvSo2gbZG+N3Y2quzR3GhKANqSOVhL/XfRlDsKEPTXD19fnNXxA+Jj10gpM2aBGhSChriUAFnUkW8LVRa5gPm8aecz9qRZsNurjsVOebKLiIZ+DLRV0hoVAoeAJIpzJUB8mmAZkHkz/cL5C490AHZxVK3BU7VXPh7MjUkgFcSI1AYs6G+da3QmS5YzA/wcfLOiBLySxRhHP18bGXi2FDPJu1gxALasGEiZNyzn8MsaiMfFjMVZID79bEKdHW1bM5213KjfTVlCoMU2XVya1N8IZVvei/Nx/qdg4MHG6Ay/v/2dLyHGH8gnktMnJybire+GM/SdlnKRLrjKnqHxhMqyRkXt1V5wFTdFH9jlOat7S482fUWap81zswOue+fA6fR0oR6qkY9GJBakKr+x2b3TC5wIYwgWRRsOjK3GMA6DC3QPArHggZTz827QvKWhw6uUSkHQaawdbewxrn+0I+pzaDuBwnRTxxfuantQEeulUAz0xc8spQ4HCO9CXWY=
